In [ ]:
import pandas as pd
import numpy as np

In [ ]:
my_df = pd.DataFrame({"A" : [1,2,4,np.nan,5,np.nan,7],
                      "B" : [4,np.nan,7,np.nan,1,np.nan,2]})
my_df

A    B
0  1.0  4.0
1  2.0  NaN
2  4.0  7.0
3  NaN  NaN
4  5.0  1.0
5  NaN  NaN
6  7.0  2.0

In [ ]:
#find missing values with pandas

my_df.isna()

A      B
0  False  False
1  False   True
2  False  False
3   True   True
4  False  False
5   True   True
6  False  False

In [ ]:
my_df.isna().sum()

A    2
B    3
dtype: int64

In [ ]:
#dropping the missing values with pandas
#if it has missing in the row it is drop whole row
my_df.dropna()

A    B
0  1.0  4.0
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [ ]:
my_df.dropna(how="any")

A    B
0  1.0  4.0
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [ ]:
# if it two columns it has the values Null only then it is dropping the row
my_df.dropna(how="all")

A    B
0  1.0  4.0
1  2.0  NaN
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [ ]:
my_df.dropna(how="any", subset=["A"])

A    B
0  1.0  4.0
1  2.0  NaN
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [ ]:
my_df.dropna(how="any", inplace=True)
my_df

A    B
0  1.0  4.0
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [ ]:
my_df.dropna(how = "any", subset = ["A"])

A    B
0  1.0  4.0
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [ ]:
my_df.dropna(how = "any", inplace = True)
my_df

A    B
0  1.0  4.0
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [ ]:
# Filling Missing Values with Pandas

In [ ]:
my_df1 = pd.DataFrame({"A" : [1,2,4,np.nan,5,np.nan,7],
                      "B" : [4,np.nan,7,np.nan,1,np.nan,2]})
my_df1

A    B
0  1.0  4.0
1  2.0  NaN
2  4.0  7.0
3  NaN  NaN
4  5.0  1.0
5  NaN  NaN
6  7.0  2.0

In [ ]:
my_df.fillna(value = 100)

A    B
0  1.0  4.0
2  4.0  7.0
4  5.0  1.0
6  7.0  2.0

In [ ]:
mean_value=my_df1["A"].mean()
mean_value

np.float64(3.8)

In [ ]:
my_df1["A"].fillna(value=mean_value)

0    1.0
1    2.0
2    4.0
3    3.8
4    5.0
5    3.8
6    7.0
Name: A, dtype: float64

In [ ]:
#Applying to whole dataframe to all columns
my_df1.fillna(value=my_df1.mean(),inplace=True)
my_df1

A    B
0  1.0  4.0
1  2.0  3.5
2  4.0  7.0
3  3.8  3.5
4  5.0  1.0
5  3.8  3.5
6  7.0  2.0

Imputer

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer

In [ ]:
my_df2 = pd.DataFrame({"A" : [1,4,7,10,13],
                      "B" : [3,6,9,np.nan,15],
                      "C" : [2,5,np.nan,11,np.nan]})
my_df2

A     B     C
0   1   3.0   2.0
1   4   6.0   5.0
2   7   9.0   NaN
3  10   NaN  11.0
4  13  15.0   NaN

In [ ]:
#now we will call the class
imputer =SimpleImputer()

In [ ]:
#first we will apply fit and then do the tranform
imputer.fit(my_df2)
imputer.transform(my_df2)

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [ ]:
my_df2_1=imputer.transform(my_df2)
my_df2_1

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SimpleImputer was fitted with feature names
  warnings.warn(


array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [ ]:
#we can apply fit and tranform at a time but not recommended
imputer.fit_transform(my_df2)

array([[ 1.  ,  3.  ,  2.  ],
       [ 4.  ,  6.  ,  5.  ],
       [ 7.  ,  9.  ,  6.  ],
       [10.  ,  8.25, 11.  ],
       [13.  , 15.  ,  6.  ]])

In [ ]:
#if u see previously it is in array so we converted to dataframe
my_df2_2=pd.DataFrame(imputer.fit_transform(my_df2), columns = ['A', 'B', 'C'])
my_df2_2

A      B     C
0   1.0   3.00   2.0
1   4.0   6.00   5.0
2   7.0   9.00   6.0
3  10.0   8.25  11.0
4  13.0  15.00   6.0

KNNImputer

In [ ]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

In [ ]:
my_df3 = pd.DataFrame({"A" : [1,2,3,4,5],
                      "B" : [1,1,3,3,4],
                      "C" : [1,2,9,np.nan,20]})
my_df3

A  B     C
0  1  1   1.0
1  2  1   2.0
2  3  3   9.0
3  4  3   NaN
4  5  4  20.0

In [ ]:
knn_imputer=KNNImputer() # calling the class

In [ ]:
knn_imputer = KNNImputer(n_neighbors = 1)
#if u see the column c has. null value the nearest neighbor since 1 that value is 9

In [ ]:
knn_imputer = KNNImputer(n_neighbors = 2)
#consider the 2 nearest neighbors when estimating a missing value. For numerical data, the

In [ ]:
knn_imputer = KNNImputer(n_neighbors = 2, weights = "distance")


In [ ]:
knn_imputer.fit_transform(my_df3)

array([[ 1.        ,  1.        ,  1.        ],
       [ 2.        ,  1.        ,  2.        ],
       [ 3.        ,  3.        ,  9.        ],
       [ 4.        ,  3.        , 13.55634919],
       [ 5.        ,  4.        , 20.        ]])

In [ ]:
my_df3_1 = pd.DataFrame(knn_imputer.fit_transform(my_df3), columns = my_df.columns)
my_df3_1

A    B          C
0  1.0  1.0   1.000000
1  2.0  1.0   2.000000
2  3.0  3.0   9.000000
3  4.0  3.0  13.556349
4  5.0  4.0  20.000000